workflows:
  apscroworld-workflow:
    name: Apscroworld Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Reconstruct Project Structure
        script: |
          # حفظ كود اللب واللوجو والمواصفات في مكان مؤقت
          mkdir -p ../temp_assets
          cp -r lib ../temp_assets/
          cp pubspec.yaml ../temp_assets/
          cp -r assets ../temp_assets/ 2>/dev/null || :
          
          # مسح كل شيء وإنشاء مشروع فلوتر نظيف تماماً
          cd ..
          rm -rf $CM_REPO_SLUG
          flutter create --project-name apscroworld_app $CM_REPO_SLUG
          
          # إعادة ملفاتنا الأصلية للمشروع الجديد
          cd $CM_REPO_SLUG
          cp -r ../temp_assets/lib/* ./lib/
          cp ../temp_assets/pubspec.yaml ./
          cp -r ../temp_assets/assets ./ 2>/dev/null || :
      - name: Get dependencies
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
