workflows:
  apscroworld-workflow:
    name: Apscroworld Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Hard Reset and Reconstruct
        script: |
          # 1. حفظ ملفاتنا الحيوية في الذاكرة المؤقتة للماشين
          cp -r lib ../lib_backup
          cp pubspec.yaml ../pubspec_backup
          [ -d "assets" ] && cp -r assets ../assets_backup || mkdir ../assets_backup
          
          # 2. تنظيف شامل للمجلد الحالي (حذف كل شيء بما فيه المجلدات المخفية)
          rm -rf ./* ./.* 2>/dev/null || true
          
          # 3. إنشاء مشروع فلوتر جديد تماماً في نفس المكان
          flutter create --project-name apscroworld_app .
          
          # 4. استعادة ملفاتنا الأصلية فوق المشروع الجديد
          rm -rf lib
          cp -r ../lib_backup ./lib
          cp ../pubspec_backup ./pubspec.yaml
          cp -r ../assets_backup ./assets 2>/dev/null || true
          
      - name: Get dependencies
        script: flutter packages pub get
        
      - name: Build APK
        script: |
          # إضافة سطر التأكد من استخدام أحدث إصدار من Gradle
          flutter build apk --release --no-pub
          
    artifacts:
      - build/app/outputs/apk/release/*.apk
