workflows:
  android-release:
    name: Secure Chat Final Build
    instance_type: mac_mini_m2
    scripts:
      - name: Build APK
        script: flutter build apk --release --tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
