workflows:
  main-workflow:
    name: Apscroworld Final Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter packages pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
