workflows:
  android-release:
    name: Secure Chat Icon Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Setup Project
        script: |
          flutter create --platforms android --org com.cardiachat --project-name secure_chat_app . 
          
      - name: Clean and Get Dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Generate App Icons
        script: |
          # التأكد من وجود الصورة برمجياً قبل البدء
          ls -lh assets/icon/app_icon.png
          dart run flutter_launcher_icons
          
      - name: Build APK
        script: |
          flutter build apk --release --tree-shake-icons
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
