workflows:
  default-workflow:
    name: Apscroworld Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android APK
        script: flutter build apk --release --no-pub
    artifacts:
      - build/app/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
