workflows:
  apscroworld-workflow:
    name: Apscroworld Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - default
      vars:
        PACKAGE_NAME: "com.apscroworld.app"
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --release --no-pub
    artifacts:
      - build/app/outputs/apk/release/*.apk
