workflows:
  android-release:
    name: Full Secure Chat Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Setup Project and Android Folder
        script: |
          # إنشاء مجلدات أندرويد وملحقاتها
          flutter create --platforms android --org com.cardiachat --project-name secure_chat_app . 
          
      - name: Add All Permissions & Features
        script: |
          # إضافة صلاحية الإنترنت وجميع ملحقات المانيفست
          sed -i '' 's|<manifest|<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n    <uses-permission android:name="android.permission.INTERNET"/>|' android/app/src/main/AndroidManifest.xml

      - name: Generate App Icons
        script: |
          flutter pub get
          # تشغيل أمر الأيقونات مع ضمان الاستمرار حتى لو حدث خطأ
          dart run flutter_launcher_icons || echo "Icon generation failed, but continuing to build app..."
          
      - name: Build Final APK
        script: |
          # بناء التطبيق كاملاً مع كل الملحقات
          flutter build apk --release --tree-shake-icons
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
