workflows:
  android-release:
    name: Secure Chat Final Firebase Build
    instance_type: mac_mini_m2
    scripts:
      - name: Generate Android Folder
        script: |
          # 1. إنشاء المشروع
          flutter create --platforms android --org com.cardiachat --project-name secure_chat_app . 
          
          # 2. حقن صلاحية الإنترنت داخل ملف AndroidManifest الذي تم إنشاؤه للتو
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml
          
      - name: Build APK
        script: |
          flutter build apk --release --tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
