workflows:
  android-release:
    name: Secure Chat Icon Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Setup and Clean
        script: |
          flutter create --platforms android --org com.cardiachat --project-name secure_chat_app . 
          flutter clean
          flutter pub get
          
      - name: Add Internet Permission
        script: |
          sed -i '' 's|<manifest|<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n    <uses-permission android:name="android.permission.INTERNET"/>|' android/app/src/main/AndroidManifest.xml

      - name: Generate App Icons
        script: |
          flutter pub get
          dart run flutter_launcher_icons
          
      - name: Build APK
        script: |
          flutter build apk --release --tree-shake-icons
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
