workflows:
  release-build:
    name: Build Apscroworld Release
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Fetch Dependencies
        script: flutter packages pub get
      - name: Generate App Icons
        script: flutter pub run flutter_launcher_icons
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - admin@apscroworld.com # ضع إيميلك هنا
