workflows:
  android-release:
    name: Secure Chat Final Icon Build
    instance_type: mac_mini_m2
    scripts:
      - name: Fetch and Generate
        script: |
          # التأكد من جلب الملفات المرفوعة يدوياً
          git pull origin main
          
          # إنشاء مجلد أندرويد
          flutter create --platforms android --org com.cardiachat --project-name secure_chat_app . 
          
          # حقن صلاحية الإنترنت
          sed -i '' 's|<manifest|<manifest xmlns:android="http://schemas.android.com/apk/res/android"> \n    <uses-permission android:name="android.permission.INTERNET"/>|' android/app/src/main/AndroidManifest.xml
          
          # توليد الأيقونات
          dart run flutter_launcher_icons
          
      - name: Build APK
        script: |
          flutter build apk --release --tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
