workflows:
  android-release:
    name: Secure Chat Final Firebase Build
    instance_type: mac_mini_m2
    scripts:
      - name: Generate Android Folder
        script: |
          # إنشاء المشروع بالهوية الصحيحة ليتوافق مع ملف Firebase
          flutter create --platforms android --org com.cardiachat --project-name secure_chat_app . 
      - name: Build APK
        script: |
          flutter build apk --release --tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
